% Usage:
% [calStructOBJ, inputArgIsACalStructOBJ] = ObjectToHandleCalOrCalStruct(calOrCalStruct);
%
% Method that returns a @CalStruct object to handle a calOrCalStruct input.
% If the input is already a @CalStruct object, the same object is returned.
% If the input is a cal struct, a @CalStruct object is instantiated with
% this cal, and returned to the user.
%
% 5/07/14     npc   Wrote it.
%

function [calStructOBJ, inputArgIsACalStruct] = ObjectToHandleCalOrCalStruct(calOrCalStruct)
%    
    if (isa(calOrCalStruct, 'CalStruct'))
        % The input argument (calOrCalStructOBJ) is a pointer to a @CalStruct object, so we will use
        % it directly. We rename it to indicate that it is a @CalStruct object, not
        % a cal structure.
        calStructOBJ = calOrCalStruct;
        inputArgIsACalStruct = true;
    elseif isstruct(calOrCalStruct)
        % The input argument (calOrCalStructOBJ) is a cal structure. We will instantiate a 
        % @CalStruct object to manage it, independently of its format
        % (new-style, generated by OOcalibration, or old-style, generated by mglCalibrateMonSpd).
        calStructOBJ = CalStruct(calOrCalStruct, 'verbosity', 0); 
        inputArgIsACalStruct = false;
    elseif isempty(calOrCalStruct)
        error('input argument is []. Must be either a @CalStruct object (preferred) or a cal struct (old-style). For more info: doc CalStruct.');
    else
        error('First input argument must be either a @CalStruct object (preferred) or a cal struct (old-style). For more info: doc CalStruct.'); 
    end
end