/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "monado_metrics.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(monado_metrics_Version, monado_metrics_Version, AUTO)


PB_BIND(monado_metrics_SessionFrame, monado_metrics_SessionFrame, AUTO)


PB_BIND(monado_metrics_Used, monado_metrics_Used, AUTO)


PB_BIND(monado_metrics_SystemFrame, monado_metrics_SystemFrame, AUTO)


PB_BIND(monado_metrics_SystemGpuInfo, monado_metrics_SystemGpuInfo, AUTO)


PB_BIND(monado_metrics_SystemPresentInfo, monado_metrics_SystemPresentInfo, AUTO)


PB_BIND(monado_metrics_Record, monado_metrics_Record, AUTO)



