/*
    PsychtoolboxGL/Source/Common/PsychHID/PsychHIDKbQueueCheck.c

    PROJECTS:

        PsychHID only.

    PLATFORMS:

        All.

    AUTHORS:

        rwoods@ucla.edu                 rpw
        mario.kleiner.de@gmail.com      mk

    HISTORY:
        8/19/07  rpw        Created.
        8/23/07  rpw        Added PsychHIDQueueFlush to documentation; removed call to PsychHIDVerifyInit()

*/

#include "PsychHID.h"

PsychError PSYCHHIDKbQueueCheck(void)
{
    static char useString[] = "[keyIsDown, firstKeyPressTimes, firstKeyReleaseTimes, lastKeyPressTimes, lastKeyReleaseTimes]=PsychHID('KbQueueCheck' [, deviceIndex])";
    static char synopsisString[] =
        "Checks a queue for keyboard or button events generated by a device.\n"
        "PsychHID('KbQueueCreate') must be called before this routine "
        "and PsychHID('KbQueueStart') must then be called for any events "
        "to be returned.\n"
        "The optional 'deviceIndex' is the index of the HID input device whose queue should be checked. "
        "If omitted, the queue of the default device will be checked.\n";

    static char seeAlsoString[] = "KbQueueCreate, KbQueueStart, KbQueueStop, KbQueueFlush, KbQueueRelease";

    int deviceIndex;

    PsychPushHelp(useString, synopsisString, seeAlsoString);
    if (PsychIsGiveHelp()) {PsychGiveHelp(); return(PsychError_none);};

    PsychErrorExit(PsychCapNumOutputArgs(5));
    PsychErrorExit(PsychCapNumInputArgs(1));

    deviceIndex = -1;
    PsychCopyInIntegerArg(1, kPsychArgOptional, &deviceIndex);

    PsychHIDOSKbQueueCheck(deviceIndex);

    return(PsychError_none);
}

PsychError PSYCHHIDKbQueueGetEvent(void)
{
    static char useString[] = "[event, navail] = PsychHID('KbQueueGetEvent' [, deviceIndex][, maxWaitTimeSecs=0])";
    static char synopsisString[] =
        "Checks a queue for input events generated by a device.\n"
        "PsychHID('KbQueueCreate') must be called before this routine and PsychHID('KbQueueStart') "
        "must then be called for any events to get recorded into the event buffer.\n"
        "The optional 'deviceIndex' is the index of the HID input device whose queue should be queried. "
        "If omitted, the queue of the default device will be queried.\n"
        "'maxWaitTimeSecs' is an optional maximum wait time for a new event in seconds. "
        "It defaults to zero, which means to just poll for a pending event. A positive value "
        "will wait until either at least one event arrived or the given amount of time elapses, "
        "whatever comes first.\n"
        "If there are any events queued, the oldest one is returned in the struct "
        "'event', otherwise an empty matrix is returned. The number of queued events "
        "remaining in the queue after fetching is returned in 'navail'.\n"
        "The returned 'event' struct, if any, currently contains the following fields:\n\n"
        "'Type' = Event type:\n"
        " 0 = Key/Button press/release on a keyboard, keypad, mouse, joystick, gamepad, digitizer tablet etc.\n"
        " 1 = mouse pointer, joystick, gamepad, digitizer tablet tool motion or change of some other property.\n"
        "\n"
        "'Time' = The GetSecs time when the event was received.\n"
        "'Keycode' = The KbCheck / KbName style keycode of the key, or the number of the button that "
        "triggered this event on non-keyboard devices. 0 for pure motion events or other non-press/release events.\n"
        "'Pressed' = 1 for a key/button press event, 0 for a key/button release event. For non-press/release events, "
        "e.g., mouse or joystick movements, it may report if any button on that device is pressed, but don't count on it.\n"
        "'CookedKey' = Keycode translated into a GetChar() style ASCII character code. Or zero if key "
        "does not have a corresponding character. Or -1 if mapping is unsupported for given event.\n"
        "'ButtonStates' = A binary value whose different bits signal the state of device buttons, ie.\n"
        "bitand (Buttons, 2^i) > 0 menas that the i'th button on the device was pressed at that time. "
        "Currently only the first 32 buttons on a device are reported, and this feature may only work on Linux "
        "with X11 windowing system for some event types like keyboard, mouse/joystick movements, so use of this "
        "is not portable!\n"
        "'Motion' = 1 if this is a motion event, e.g., mouse, joystick, knob motion, 0 otherwise.\n"
        "'X' = For 'Type' 1 motion events, the x position of the pointer associated with the pointing device.\n"
        "'Y' = For 'Type' 1 motion events, the y position of the pointer associated with the pointing device.\n"
        "For 'Type' 0 events, this may report the location of the mouse pointer when a keyboard key was pressed or "
        "released, at least on Linux with X11 windowing system, but not neccessarily on other operating systems or "
        "windowing systems, so don't rely on it being portable!\n"
        "'Valuators' = For 'Type' 1 motion events, a vector with the values of various device-specific valuators, e.g., extra "
        "axis, levers or knobs on a joystick or gamepad, or the mouse-wheel position on a mouse, or the touch "
        "pressure on a touchpad, or pen pressure, orientation, hovering distance on a digitizer tablet. The first "
        "two Valuators entries are identical to 'X' and 'Y' at all times. The meaning of the different elements of "
        "the vector is completely device specific. The content is also operating system specific for the same device, "
        "so scripts making use of these values may not be portable across devices or operating systems.\n";
    static char seeAlsoString[] = "KbQueueCreate, KbQueueStart, KbQueueStop, KbQueueFlush, KbQueueRelease";

    int deviceIndex;
    unsigned int navail;
    double maxWaitTimeSecs;

    PsychPushHelp(useString, synopsisString, seeAlsoString);
    if (PsychIsGiveHelp()) {PsychGiveHelp(); return(PsychError_none);};

    PsychErrorExit(PsychCapNumOutputArgs(2));
    PsychErrorExit(PsychCapNumInputArgs(2));

    deviceIndex = -1;
    PsychCopyInIntegerArg(1, kPsychArgOptional, &deviceIndex);

    maxWaitTimeSecs = 0;
    PsychCopyInDoubleArg(2, kPsychArgOptional, &maxWaitTimeSecs);

    // Get next event from buffer, return it as 1st return argument:
    navail = PsychHIDReturnEventFromEventBuffer(deviceIndex, 1, maxWaitTimeSecs);
    PsychCopyOutDoubleArg(2, FALSE, (double)navail);

    return(PsychError_none);
}
