// This C++ file is the interface between GNU/Octave and Psychtoolbox
// module FontInfo. It defines the entry-point function FFontInfo and the online
// help for FontInfo. The function itself (see bottom of file) is just a
// wrapper around octFunction(), the real command dispatcher defined in
// the PsychScriptingGlue.cc file.
// This file is autogenerated, please do not edit!
//

#ifdef PTBOCTAVE
#define PTBMODULE_FontInfo
#include <octave/oct.h>

extern "C" {
  // mex.cc names both mexFunction (c) and MEXFUNCTION (Fortran)
  // but the mex file only defines one of them, so define the other
  // here just to keep the linker happy, but don't ever call it.
  void F77_FUNC(mexfunction,MEXFUNCTION)() {}
  const char *mexFunctionName = "FontInfo";
} ;

DEFUN_DLD(FontInfo, args, nargout,
"FontInfo not directly documented. Try the following:\n   type(file_in_loadpath('FontInfo.m'))\n")
{
  octave_value_list octFunction(const octave_value_list &, const int);
  return octFunction(args, nargout);
}
#endif
